use_frameworks!
platform :ios, '9.0'

target 'CombinationGenerator_Example' do
  pod 'CombinationGenerator', :path => '../'

  target 'CombinationGenerator_Tests' do
    inherit! :search_paths

    
  end
end
