#if !canImport(ObjectiveC)
import XCTest

extension CombinationGeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CombinationGeneratorTests = [
        ("test2Value2Combination", test2Value2Combination),
        ("testEmptyCombinations", testEmptyCombinations),
        ("testGenerateCombinations", testGenerateCombinations),
        ("testPerformanceGenerateThousandExamples", testPerformanceGenerateThousandExamples),
        ("testSingleValue", testSingleValue),
        ("testSingleValue2Combination", testSingleValue2Combination),
        ("testSingleValueEmptyContent", testSingleValueEmptyContent),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CombinationGeneratorTests.__allTests__CombinationGeneratorTests),
    ]
}
#endif
